#pragma once
#include <iostream>
#include <fstream>
#include <ostream>
#include <istream>
#include <iomanip>
#include <vector>
#include <list>
#include <initializer_list>
#include <stack>
#include <queue>
#include <deque>
#include <array>
#include <memory>
#include <utility>
#include <functional>
#include <atomic>
#include <algorithm>
#include <any>
#include <optional>
#include <map>
#include <set>
#include <cctype>
#include <string>
#include <chrono>
#include <forward_list>
#include <regex>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <span>
#include <filesystem>
#include <random>
#include <cstdlib>
